# -*- coding: utf-8 -*-
"""project-ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160hkvQPiLRnpeaa0qXCeP7x9wLmwN0Al
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

from mlxtend.plotting import plot_decision_regions
import missingno as msno
from pandas.plotting import scatter_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

diabetes_df = pd.read_csv('/content/sample_data/diabetes.csv')
diabetes_df.head()

diabetes_df.columns

diabetes_df.info()

diabetes_df.describe()

"""count = non missing values,mean = average value in column,std= standard deviation,min=min value in the column , 25%= the value below 25,50%=mid value,75%=the value belo 75,max=height


"""

diabetes_df.isnull().head(10)

"""check the missing values if the value is missing output is true else false"""

diabetes_df.isnull().sum()

"""calculate the no of missing values"""

diabetes_df_copy = diabetes_df.copy(deep = True)
diabetes_df_copy[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']] = diabetes_df_copy[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']].replace(0,np.NaN)


print(diabetes_df_copy.isnull().sum())

p = diabetes_df.hist(figsize = (20,20))

"""X axis = values
Y axis = numbers
"""

diabetes_df_copy['Glucose'].fillna(diabetes_df_copy['Glucose'].mean(), inplace = True)
diabetes_df_copy['BloodPressure'].fillna(diabetes_df_copy['BloodPressure'].mean(), inplace = True)
diabetes_df_copy['SkinThickness'].fillna(diabetes_df_copy['SkinThickness'].median(), inplace = True)
diabetes_df_copy['Insulin'].fillna(diabetes_df_copy['Insulin'].median(), inplace = True)
diabetes_df_copy['BMI'].fillna(diabetes_df_copy['BMI'].median(), inplace = True)

p = diabetes_df_copy.hist(figsize = (20,20))

p = msno.bar(diabetes_df)

plt.figure(figsize=(12,10))

p = sns.heatmap(diabetes_df.corr(), annot=True,cmap ='RdYlGn')

"""It shows the relationship betwen the two varibles +1: Perfect positive correlation
As one variable increases, the other also increases proportionally.
0: No correlation
Changes in one variable do not predict changes in the other.
-1: Perfect negative correlation
As one variable increases, the other decreases proportionally.
"""

sc_X = StandardScaler()
X =  pd.DataFrame(sc_X.fit_transform(diabetes_df_copy.drop(["Outcome"],axis = 1),), columns=['Pregnancies',
'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])
X.head()

X = diabetes_df.drop('Outcome', axis=1)
y = diabetes_df['Outcome']

"""x= features , y = targeted variable"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33,
                                                    random_state=7)

from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train, y_train)

"""200 no of decision trees"""

rfc_train = rfc.predict(X_train)
from sklearn import metrics

print("Accuracy_Score =", format(metrics.accuracy_score(y_train, rfc_train)))

"""Accuracy= Total Number of Predictions /Number of Correct Predictions



"""

from sklearn import metrics

predictions = rfc.predict(X_test)
print("Accuracy_Score =", format(metrics.accuracy_score(y_test, predictions)))

rfc.feature_importances_

"""Returns an array of numbers, each representing the importance of the corresponding feature in X_train."""

(pd.Series(rfc.feature_importances_, index=X.columns).plot(kind='barh'))

import pickle

saved_model = pickle.dumps(rfc)
rfc_from_pickle = pickle.loads(saved_model)

rfc_from_pickle.predict(X_test)

rfc.predict([[0,137,40,35,168,43.1,2.228,33]]) #4th patient

rfc.predict([[10,101,76,48,180,32.9,0.171,63]])  # 763 th patient

rfc.predict([[1,85,66,29,0,26.6,0.351,31]]) # 1st patient

color_wheel = {1: "#0392cf", 2: "#7bc043"}
colors = diabetes_df["Outcome"].map(lambda x: color_wheel.get(x + 1))
print(diabetes_df.Outcome.value_counts())
p=diabetes_df.Outcome.value_counts().plot(kind="bar")